name: Deploy to NPM 🚀

on:
  push:
    branches:
      - "release/**"
  release:
    types: [created]

jobs:
  deploy-npm:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"
          token: ${{ secrets.NPM_TOKEN }}
          always_auth: true
      - run: yarn install
      - run: yarn build --print-label
      - run: yarn test
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
